demo:
  app:
    itunes:
      hostUrl: "itunes.apple.com"

spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
springdoc:
  swagger-ui:
    path: "/swagger"