demo:
  app:
    itunes:
      hostUrl: ${ITUNES_HOST:itunes.apple.com}

spring:
  h2:
    console:
      enabled: true
      path: "/${H2_PATH:h2}"
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  cache:
    cache-names: itunes-artists
    caffeine:
      spec: maximumSize=500, expireAfterAccess=10m

springdoc:
  swagger-ui:
    path: "/${SWAGGER_URL:swagger}"
